### PR TITLE
Use dependencies.io js-lerna support

### PR DESCRIPTION
**Pull request by davegaeddert**
@nickbalestra did you get a chance to try the "js-lerna" collector/actor? I think it should pretty much work out of the box. The only other thing I had to do was add "package-lock.json" to your `.gitignore`. Not sure if that's how you want to deal with it. You could also use the `npmClientArgs` to pass `--no-package-lock` to `lerna bootstrap`: https://github.com/lerna/lerna#bootstrap

Let me know if you have any questions, you can look at my repo fork for examples of PRs that were created.

### CODE REVIEW

**Comment by nickbalestra** [comment]
Thank you very much @davegaeddert for this!
I went through the [fork you did](https://github.com/davegaeddert/base-templates) and the [PRs](https://github.com/davegaeddert/base-templates/pulls) that `dependencies` generated. And it seems that those are way fewer then if manually setting up a `js-npm` collectors/actors for each package in the monorepo. 

As I feel that checking per package independently is safer, I'll close this PR for now.

**Comment by davegaeddert** [comment]
Good catch. Looking at it now, I think the difference is whether or not you're getting updates for other packages that are in this repo -- like [the one you pointed out to me](https://github.com/opencomponents/base-templates/pull/118/files). The way our lerna collector works right now, it skips the other lerna packages in the repo since lerna just symlinks those together, instead of actually pulling from npm... Do you want those updates too? I can see how that would make sense.

**Comment by davegaeddert** [comment]
But you're right, manually using a `js-npm` collector/actor on each package will work just fine for how your repo is set up, I think.

**Comment by nickbalestra** [comment]
Yes I think it would make sense to have that with the lerna collector/actor but then you can just reproduce that with manually using `js-npm` collectors/actors, so I think is ok as it now. Thanks for clarifying it.

**Pull request closed without merging**
